# Generated by Django 4.2.7 on 2023-11-05 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "send_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время и дата рассылки"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Раз в день"),
                            ("weekly", "Раз в неделю"),
                            ("monthly", "Раз в месяц"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                            ("finished", "Завершена"),
                        ],
                        default=(
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                            ("finished", "Завершена"),
                        ),
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Тема письма"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "send_from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
                (
                    "send_to_client",
                    models.ManyToManyField(
                        related_name="client",
                        to="home.homeclient",
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "permissions": [
                    ("Can_view_any_newsletters", "Can view any mailings"),
                    ("You_can_disable_newsletters", "Can disable mailings"),
                    ("They_cannot_edit_mailings.", "Cannot edit mailings."),
                    ("Can't_manage_the_mailing_list", "Cannot manage mailing list"),
                    (
                        "Cannot_change_mailings_and_messages",
                        "Cannot change mailings and messages",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время последней попытки"
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message_email.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Логи рассылка",
                "verbose_name_plural": "Логи рассылки",
            },
        ),
    ]
