# Generated by Django 4.2.7 on 2023-11-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_delete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                blank=True, null=True, verbose_name="Содержимое статьи"
            ),
        ),
    ]
